version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: make
       - run: mkdir build && cp paper.pdf build/
       - run: perl scripts/latexcount.pl paper.tex
       - run: perl scripts/texcount.pl paper.tex
       - store_artifacts:
           path: build/

