version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: make
       - run: mkdir build && cp paper.pdf build/
       - store_artifacts:
           path: build/

